name: Build

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v5
              with:
                  node-version: "latest"
            - name: Check out the repository code
              uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - name: Build front-end
              run: |
                  cd ${{ github.workspace }}/solid-src
                  pnpm i
                  pnpm build
            - name: Package application
              run: |
                  cd ${{ github.workspace }}
                  wget https://github.com/neutralinojs/neutralinojs/releases/download/v6.3.0/neutralinojs-v6.3.0.zip
                  unzip neutralinojs-v6.3.0.zip -d bin/
                  pnpx @neutralinojs/neu build
            - uses: actions/upload-artifact@v4
              with:
                  name: vencoder-experimental
                  path: ${{ github.workspace }}/dist/vencoder/
